name: linux-test
on: [push, pull_request]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    container: rust:1-bookworm
    defaults:
      run:
        working-directory: src-tauri
    steps:
      - uses: actions/checkout@v4

      # ---- Linux GUI deps for gtk/gdk/tauri ----
      - name: Install system deps (GTK/WebKit)
        run: |
          apt-get update
          apt-get install -y \
            pkg-config \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      # React tests (if present)
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: JS tests
        if: hashFiles('web/package.json') != ''
        working-directory: web
        run: |
          npm ci
          npm test -- --ci --watch=false

      # Rust tests
      - name: Rust tests
        run: cargo test --all --locked --verbose
