name: linux-test
on: [push, pull_request]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    container: rust:1-bookworm

    defaults:
      run:
        working-directory: src-tauri

    steps:
      - uses: actions/checkout@v4

      # React tests still happen in web/
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: JS tests
        if: hashFiles('web/package.json') != ''
        working-directory: web
        run: |
          npm ci
          npm test -- --ci --watch=false

      - name: Rust tests
        run: cargo test --all --locked --verbose
