name: linux-test
on: [push, pull_request]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    container: rust:1-bookworm # Use the official Rust image with Debian Bookworm. So we dont need to install rust
    defaults:
      run:
        working-directory: src-tauri # This is because this is where Cargo.toml is
    steps:
      - uses: actions/checkout@v4

      # ---- Linux GUI deps for gtk/gdk/tauri An image including this does not exist yet to our knowlegde----
      - name: Install system deps (GTK/WebKit + audio)
        run: |
          apt-get update
          apt-get install -y \
            pkg-config \
            libasound2-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      # Rust tests (only files inside src-tauri/tests/)
      - name: Rust tests
        run: |
          for t in tests/*.rs; do
            name=$(basename "$t" .rs)
            cargo test --test "$name" --locked --verbose
          done
