name: linux-appdoesrun
on: [push, pull_request]

jobs:
  linux-smoke:
    runs-on: ubuntu-latest
    container: rust:1-bookworm
    defaults:
      run:
        working-directory: src-tauri
    steps:
      - uses: actions/checkout@v4

      - name: Install system deps
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            pkg-config \
            libasound2-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            xvfb\
            xauth

      - name: Smoke run (build + start app, fail on warnings)
        env:
          RUSTFLAGS: "-D warnings"
        run: |
          xvfb-run -a cargo run --release --locked --verbose &
          PID=$!
          sleep 240
          kill $PID || true