name: linux-app-does-run
on: [push, pull_request]

jobs:
  linux-app-does-run:
    runs-on: ubuntu-latest
    container: rust:1-bookworm # Use the official Rust image with Debian Bookworm. So we dont need to install rust
    defaults:
      run:
        working-directory: src-tauri # This is because this is where Cargo.toml is
    steps:
      - uses: actions/checkout@v4

      # ---- Linux GUI deps for gtk/gdk/tauri An image including this does not exist yet to our knowlegde----
      - name: Install system deps (GTK/WebKit + audio)
        run: |
          apt-get update
          apt-get install -y \
            pkg-config \
            libasound2-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      # Build the Tauri app
      - name: Build Tauri app
        run: |
          cargo build --release

      # Run the built app in the background and kill it after 10 seconds
      - name: Run Tauri app and verify it starts
        run: |
          ./target/release/meow & # Start the app in the background
          APP_PID=$! # Get the process ID of the last background command
          sleep 10 # Wait for 10 seconds to let the app initialize
          kill $APP_PID # Terminate the app after verification