name: windows-doesrun
on: [push, pull_request]

jobs:
  smoke:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src-tauri
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Build + run
        env:
          RUSTFLAGS: "-D warnings"
        run: cargo run --release --locked --verbose
